import { useEffect, useState } from "react";
import { categoriasApi, productosApi } from "../api/api";
import ErrorMessage from "../components/ErrorMessage";
import Loading from "../components/Loading";
import { formatCurrency } from "../utils/formatCurrency";

const emptyProduct={nombre:"",descripcion:"",precio:"",categoriaId:"",disponible:true};
export default function Menu(){const[categories,setCategories]=useState([]),[products,setProducts]=useState([]),[catName,setCatName]=useState(""),[catEdit,setCatEdit]=useState(null),[form,setForm]=useState(emptyProduct),[editing,setEditing]=useState(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[filter,setFilter]=useState("");
 const load=async()=>{try{const[c,p]=await Promise.all([categoriasApi.list(),productosApi.list(filter?{texto:filter}:{})]);setCategories(c);setProducts(p)}catch(e){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{load()},[filter]);
 const saveCat=async e=>{e.preventDefault();try{catEdit?await categoriasApi.update(catEdit,{nombre:catName}):await categoriasApi.create({nombre:catName});setCatName("");setCatEdit(null);load()}catch(e){setError(e.message)}};
 const deleteCat=async x=>{if(!confirm(`¿Seguro que desea eliminar la categoría ${x.nombre}?`))return;try{await categoriasApi.remove(x.id);load()}catch(e){setError(e.message)}};
 const saveProduct=async e=>{e.preventDefault();try{const data={...form,precio:form.precio,categoriaId:Number(form.categoriaId)};editing?await productosApi.update(editing,data):await productosApi.create(data);setEditing(null);setForm(emptyProduct);load()}catch(e){setError(e.message)}};
 const editProduct=x=>{setEditing(x.id);setForm({nombre:x.nombre,descripcion:x.descripcion||"",precio:x.precio,categoriaId:x.categoriaId,disponible:x.disponible})};
 const deleteProduct=async x=>{if(!confirm(`¿Seguro que desea eliminar ${x.nombre}?`))return;try{await productosApi.remove(x.id);load()}catch(e){setError(e.message)}};
 return <section><div className="page-title"><div><span className="eyebrow">CARTA</span><h1>Menú</h1><p>Administrá categorías, platos y disponibilidad.</p></div><input className="search" placeholder="Buscar producto..." value={filter} onChange={e=>setFilter(e.target.value)}/></div><ErrorMessage error={error}/><div className="menu-layout"><div className="panel"><h2>Categorías</h2><form className="inline" onSubmit={saveCat}><input minLength="2" required placeholder="Nueva categoría" value={catName} onChange={e=>setCatName(e.target.value)}/><button className="primary">{catEdit?'Guardar':'Agregar'}</button></form><div className="category-list">{categories.map(x=><div key={x.id}><span>{x.nombre}</span><span><button onClick={()=>{setCatEdit(x.id);setCatName(x.nombre)}}>Editar</button><button className="danger-link" onClick={()=>deleteCat(x)}>×</button></span></div>)}</div></div>
 <form className="panel form" onSubmit={saveProduct}><h2>{editing?'Editar producto':'Nuevo producto'}</h2><label>Nombre<input required minLength="2" value={form.nombre} onChange={e=>setForm({...form,nombre:e.target.value})}/></label><label>Descripción<textarea maxLength="500" value={form.descripcion} onChange={e=>setForm({...form,descripcion:e.target.value})}/></label><div className="form-row"><label>Precio<input type="number" min="0.01" step="0.01" required value={form.precio} onChange={e=>setForm({...form,precio:e.target.value})}/></label><label>Categoría<select required value={form.categoriaId} onChange={e=>setForm({...form,categoriaId:e.target.value})}><option value="">Seleccionar</option>{categories.map(x=><option value={x.id} key={x.id}>{x.nombre}</option>)}</select></label></div><label className="check"><input type="checkbox" checked={form.disponible} onChange={e=>setForm({...form,disponible:e.target.checked})}/> Disponible</label><button className="primary">{editing?'Guardar cambios':'Crear producto'}</button>{editing&&<button type="button" className="ghost" onClick={()=>{setEditing(null);setForm(emptyProduct)}}>Cancelar</button>}</form></div>
 <div className="panel product-panel"><h2>Productos <span className="count">{products.length}</span></h2>{loading?<Loading/>:products.length===0?<div className="empty">No hay productos para mostrar.</div>:<div className="product-grid">{products.map(x=><article className={!x.disponible?'muted':''} key={x.id}><div><small>{x.categoriaNombre}</small><h3>{x.nombre}</h3><p>{x.descripcion||'Sin descripción'}</p></div><strong>{formatCurrency(x.precio)}</strong><span className={`pill ${x.disponible?'ok':'off'}`}>{x.disponible?'Disponible':'No disponible'}</span><div className="actions"><button onClick={()=>editProduct(x)}>Editar</button><button onClick={()=>productosApi.availability(x.id,!x.disponible).then(load).catch(e=>setError(e.message))}>{x.disponible?'Pausar':'Activar'}</button><button className="danger-link" onClick={()=>deleteProduct(x)}>Eliminar</button></div></article>)}</div>}</div></section>}

