import { useEffect, useState } from "react";
import { mesasApi } from "../api/api";
import ErrorMessage from "../components/ErrorMessage";
import Loading from "../components/Loading";

const empty={numero:"",capacidad:"",estado:"disponible"};
export default function Mesas(){const[items,setItems]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 const load=()=>mesasApi.list().then(setItems).catch(e=>setError(e.message)).finally(()=>setLoading(false));useEffect(load,[]);
 const submit=async e=>{e.preventDefault();setError("");try{const data={numero:Number(form.numero),capacidad:Number(form.capacidad),...(editing?{estado:form.estado}:{})};editing?await mesasApi.update(editing,data):await mesasApi.create(data);setForm(empty);setEditing(null);load();}catch(e){setError(e.message)}};
 const edit=x=>{setEditing(x.id);setForm({numero:x.numero,capacidad:x.capacidad,estado:x.estado})};const remove=async x=>{if(!confirm(`¿Seguro que desea eliminar la Mesa ${x.numero}?`))return;try{await mesasApi.remove(x.id);load()}catch(e){setError(e.message)}};
 const state=async(x,value)=>{try{await mesasApi.state(x.id,value);load()}catch(e){setError(e.message)}};
 return <section><div className="page-title"><div><span className="eyebrow">SALÓN</span><h1>Mesas</h1><p>Organizá la capacidad y el estado actual.</p></div></div><ErrorMessage error={error}/><div className="split"><form className="panel form" onSubmit={submit}><h2>{editing?'Editar mesa':'Nueva mesa'}</h2><label>Número<input type="number" min="1" required value={form.numero} onChange={e=>setForm({...form,numero:e.target.value})}/></label><label>Capacidad<input type="number" min="1" max="30" required value={form.capacidad} onChange={e=>setForm({...form,capacidad:e.target.value})}/></label>{editing&&<label>Estado<select value={form.estado} onChange={e=>setForm({...form,estado:e.target.value})}><option value="disponible">Disponible</option><option value="ocupada">Ocupada</option><option value="reservada">Reservada</option></select></label>}<button className="primary">{editing?'Guardar cambios':'Crear mesa'}</button>{editing&&<button type="button" className="ghost" onClick={()=>{setEditing(null);setForm(empty)}}>Cancelar</button>}</form><div className="panel table-wrap">{loading?<Loading/>:items.length===0?<div className="empty">Todavía no hay mesas. Creá la primera.</div>:<table><thead><tr><th>Mesa</th><th>Capacidad</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><strong>#{x.numero}</strong></td><td>{x.capacidad} personas</td><td><select className={`status ${x.estado}`} value={x.estado} onChange={e=>state(x,e.target.value)}><option value="disponible">Disponible</option><option value="ocupada">Ocupada</option><option value="reservada">Reservada</option></select></td><td className="actions"><button onClick={()=>edit(x)}>Editar</button><button className="danger-link" onClick={()=>remove(x)}>Eliminar</button></td></tr>)}</tbody></table>}</div></div></section>}

