import { useEffect, useState } from "react";
import { mesasApi, pedidosApi, productosApi } from "../api/api";
import ErrorMessage from "../components/ErrorMessage";
import Loading from "../components/Loading";
import { formatCurrency } from "../utils/formatCurrency";

const next={abierto:'en_preparacion',en_preparacion:'listo',listo:'entregado',entregado:'cerrado'};
const labels={abierto:'Abierto',en_preparacion:'En preparación',listo:'Listo',entregado:'Entregado',cerrado:'Cerrado',cancelado:'Cancelado'};
export default function Pedidos(){const[orders,setOrders]=useState([]),[tables,setTables]=useState([]),[products,setProducts]=useState([]),[selected,setSelected]=useState(null),[mesaId,setMesaId]=useState(""),[productId,setProductId]=useState(""),[quantity,setQuantity]=useState(1),[estado,setEstado]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 const load=async()=>{try{const[o,m,p]=await Promise.all([pedidosApi.list(estado?{estado}:{}),mesasApi.list(),productosApi.list({disponible:true})]);setOrders(o);setTables(m);setProducts(p);if(selected){const fresh=o.find(x=>x.id===selected.id);setSelected(fresh||null)}}catch(e){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{load()},[estado]);
 const create=async e=>{e.preventDefault();try{const order=await pedidosApi.create({mesaId:Number(mesaId)});setSelected(order);setMesaId("");load()}catch(e){setError(e.message)}};
 const open=async id=>{try{setSelected(await pedidosApi.get(id))}catch(e){setError(e.message)}};
 const add=async e=>{e.preventDefault();try{setSelected(await pedidosApi.addItem(selected.id,{productoId:Number(productId),cantidad:Number(quantity)}));setProductId("");setQuantity(1);load()}catch(e){setError(e.message)}};
 const changeState=async value=>{try{setSelected(await pedidosApi.state(selected.id,value));load()}catch(e){setError(e.message)}};
 const updateQty=async(item,value)=>{try{setSelected(await pedidosApi.updateItem(selected.id,item.id,Number(value)));load()}catch(e){setError(e.message)}};
 const removeItem=async item=>{try{setSelected(await pedidosApi.removeItem(selected.id,item.id));load()}catch(e){setError(e.message)}};
 const active=selected&&!["cerrado","cancelado"].includes(selected.estado);
 return <section><div className="page-title"><div><span className="eyebrow">SERVICIO</span><h1>Pedidos</h1><p>Seguí cada comanda desde la mesa hasta el cierre.</p></div><select value={estado} onChange={e=>setEstado(e.target.value)}><option value="">Todos los estados</option>{Object.entries(labels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></div><ErrorMessage error={error}/><div className="orders-layout"><div><form className="panel inline new-order" onSubmit={create}><select required value={mesaId} onChange={e=>setMesaId(e.target.value)}><option value="">Seleccionar mesa</option>{tables.filter(x=>x.estado!=='ocupada').map(x=><option key={x.id} value={x.id}>Mesa {x.numero} · {x.capacidad} personas</option>)}</select><button className="primary">Nuevo pedido</button></form><div className="panel order-list">{loading?<Loading/>:orders.length===0?<div className="empty">No hay pedidos con este filtro.</div>:orders.map(x=><button className={`order-row ${selected?.id===x.id?'selected':''}`} onClick={()=>open(x.id)} key={x.id}><span><strong>Pedido #{x.id}</strong><small>Mesa {x.mesa.numero}</small></span><span><span className={`pill ${x.estado}`}>{labels[x.estado]}</span><strong>{formatCurrency(x.total)}</strong></span></button>)}</div></div>
 <div className="panel order-detail">{!selected?<div className="empty tall">Seleccioná un pedido para ver el detalle.</div>:<><div className="detail-head"><div><small>PEDIDO #{selected.id}</small><h2>Mesa {selected.mesa.numero}</h2></div><span className={`pill ${selected.estado}`}>{labels[selected.estado]}</span></div>{active&&<form className="inline add-item" onSubmit={add}><select required value={productId} onChange={e=>setProductId(e.target.value)}><option value="">Agregar producto</option>{products.map(x=><option key={x.id} value={x.id}>{x.nombre} · {formatCurrency(x.precio)}</option>)}</select><input type="number" min="1" max="99" value={quantity} onChange={e=>setQuantity(e.target.value)}/><button className="primary">Agregar</button></form>}<div className="items">{selected.items.length===0?<div className="empty">El pedido todavía no tiene productos.</div>:selected.items.map(x=><div className="item" key={x.id}><div><strong>{x.productoNombre}</strong><small>{formatCurrency(x.precioUnitario)} c/u</small></div>{active?<input type="number" min="1" max="99" value={x.cantidad} onChange={e=>updateQty(x,e.target.value)}/>:<span>× {x.cantidad}</span>}<strong>{formatCurrency(x.subtotal)}</strong>{active&&<button className="danger-link" onClick={()=>removeItem(x)}>×</button>}</div>)}</div><div className="total"><span>Total</span><strong>{formatCurrency(selected.total)}</strong></div>{active&&<div className="detail-actions">{next[selected.estado]&&<button className="primary" onClick={()=>changeState(next[selected.estado])}>{next[selected.estado]==='cerrado'?'Cerrar pedido':`Pasar a ${labels[next[selected.estado]].toLowerCase()}`}</button>}{['abierto','en_preparacion','listo'].includes(selected.estado)&&<button className="danger" onClick={()=>confirm('¿Cancelar este pedido?')&&changeState('cancelado')}>Cancelar</button>}</div>}</>}</div></div></section>}

