import { useEffect, useState } from "react";
import { mesasApi, reservasApi } from "../api/api";
import ErrorMessage from "../components/ErrorMessage";
import Loading from "../components/Loading";
import { formatDate } from "../utils/formatDate";

const empty={nombreCliente:"",cantidadPersonas:"",fecha:"",hora:"",mesaId:"",observaciones:""};
const labels={pendiente:'Pendiente',confirmada:'Confirmada',cancelada:'Cancelada',completada:'Completada'};
export default function Reservas(){const[items,setItems]=useState([]),[tables,setTables]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[filters,setFilters]=useState({fecha:"",estado:"",texto:""}),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 const load=async()=>{try{const[r,m]=await Promise.all([reservasApi.list(filters),mesasApi.list()]);setItems(r);setTables(m)}catch(e){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{load()},[filters.fecha,filters.estado,filters.texto]);
 const submit=async e=>{e.preventDefault();try{const data={...form,cantidadPersonas:Number(form.cantidadPersonas),mesaId:Number(form.mesaId)};editing?await reservasApi.update(editing,data):await reservasApi.create(data);setEditing(null);setForm(empty);load()}catch(e){setError(e.message)}};
 const edit=x=>{setEditing(x.id);setForm({nombreCliente:x.nombreCliente,cantidadPersonas:x.cantidadPersonas,fecha:x.fecha,hora:x.hora,mesaId:x.mesaId,observaciones:x.observaciones||""})};
 const state=async(x,value)=>{try{await reservasApi.state(x.id,value);load()}catch(e){setError(e.message)}};
 const remove=async x=>{if(!confirm(`¿Seguro que desea eliminar la reserva de ${x.nombreCliente}?`))return;try{await reservasApi.remove(x.id);load()}catch(e){setError(e.message)}};
 return <section><div className="page-title"><div><span className="eyebrow">AGENDA</span><h1>Reservas</h1><p>Planificá el salón sin superposiciones.</p></div></div><ErrorMessage error={error}/><div className="split reservations"><form className="panel form" onSubmit={submit}><h2>{editing?'Editar reserva':'Nueva reserva'}</h2><label>Nombre del cliente<input required minLength="2" value={form.nombreCliente} onChange={e=>setForm({...form,nombreCliente:e.target.value})}/></label><div className="form-row"><label>Personas<input type="number" min="1" required value={form.cantidadPersonas} onChange={e=>setForm({...form,cantidadPersonas:e.target.value})}/></label><label>Mesa<select required value={form.mesaId} onChange={e=>setForm({...form,mesaId:e.target.value})}><option value="">Seleccionar</option>{tables.map(x=><option key={x.id} value={x.id}>Mesa {x.numero} · cap. {x.capacidad}</option>)}</select></label></div><div className="form-row"><label>Fecha<input type="date" required value={form.fecha} onChange={e=>setForm({...form,fecha:e.target.value})}/></label><label>Hora<input type="time" required value={form.hora} onChange={e=>setForm({...form,hora:e.target.value})}/></label></div><label>Observaciones<textarea maxLength="500" value={form.observaciones} onChange={e=>setForm({...form,observaciones:e.target.value})}/></label><button className="primary">{editing?'Guardar cambios':'Crear reserva'}</button>{editing&&<button type="button" className="ghost" onClick={()=>{setEditing(null);setForm(empty)}}>Cancelar</button>}</form>
 <div><div className="panel filters"><input type="date" value={filters.fecha} onChange={e=>setFilters({...filters,fecha:e.target.value})}/><select value={filters.estado} onChange={e=>setFilters({...filters,estado:e.target.value})}><option value="">Todos los estados</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input placeholder="Buscar cliente" value={filters.texto} onChange={e=>setFilters({...filters,texto:e.target.value})}/></div><div className="panel table-wrap">{loading?<Loading/>:items.length===0?<div className="empty">No existen reservas para los filtros seleccionados.</div>:<table><thead><tr><th>Cliente</th><th>Fecha</th><th>Mesa</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td><strong>{x.nombreCliente}</strong><small>{x.cantidadPersonas} personas</small></td><td>{formatDate(x.fecha)}<small>{x.hora} hs</small></td><td>Mesa {x.mesa.numero}</td><td><span className={`pill ${x.estado}`}>{labels[x.estado]}</span></td><td className="actions">{['pendiente','confirmada'].includes(x.estado)&&<button onClick={()=>edit(x)}>Editar</button>}{x.estado==='pendiente'&&<button onClick={()=>state(x,'confirmada')}>Confirmar</button>}{x.estado==='confirmada'&&<button onClick={()=>state(x,'completada')}>Completar</button>}{['pendiente','confirmada'].includes(x.estado)&&<button className="danger-link" onClick={()=>state(x,'cancelada')}>Cancelar</button>}{['pendiente','cancelada'].includes(x.estado)&&<button className="danger-link" onClick={()=>remove(x)}>Eliminar</button>}</td></tr>)}</tbody></table>}</div></div></div></section>}

